//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cod1._6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public string ProductArticleNumber { get; set; }
        public int ProductName { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<int> maxskid { get; set; }
        public int ProductManufacturer { get; set; }
        public int provader { get; set; }
        public int ProductCategory { get; set; }
        public Nullable<int> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string foto { get; set; }
    
        public virtual kategor kategor { get; set; }
        public virtual MUNUFF MUNUFF { get; set; }
        public virtual Namee Namee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual provader provader1 { get; set; }
    }
}
